import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import convert from 'color-convert';

// PDF Config
const PAGE_MARGIN = 40;
const SWATCH_WIDTH = 80;
const ROW_HEIGHT = 58;
const ROW_GAP = 12;
const PAGE_WIDTH = 595;   // A4
const PAGE_HEIGHT = 842;  // A4

// Normalized color values
const hexToRgbNormalized = (hex: string) => convert.hex.rgb(hex).map(c => c / 255);

export const exportPalette = async (colors: string[]) => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let y = PAGE_HEIGHT - PAGE_MARGIN;

  //---- Header ----
  page.drawText('Color Palette', {
    x: PAGE_MARGIN,
    y,
    size: 18,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.1)
  });

  y -= 18;
  page.drawText(`Exported · ${colors.length} color${colors.length !== 1 ? 's' : ''}`, {
    x: PAGE_MARGIN,
    y,
    size: 11,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric'
  });
  page.drawText(dateStr, {
    x: PAGE_WIDTH - PAGE_MARGIN - font.widthOfTextAtSize(dateStr, 10),
    y,
    size: 10,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });

  y -= 16;

  // Header divider
  page.drawLine({
    start: { x: PAGE_MARGIN, y },
    end: { x: PAGE_WIDTH - PAGE_MARGIN, y },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.85),
  });

  y -= ROW_GAP + ROW_HEIGHT;

  // ---- Rows ----
  const rowWidth = PAGE_WIDTH - PAGE_MARGIN * 2;
  const infoX = PAGE_MARGIN + SWATCH_WIDTH + 16;
  const colWidth = (rowWidth - SWATCH_WIDTH - 16) / 3;

  colors.forEach((hex) => {
    const [r, g, b] = hexToRgbNormalized(hex);
    const [cr, cg, cb, ck] = convert.hex.cmyk(hex);
    const [rr, rg, rb] = convert.hex.rgb(hex);

    // Row background
    page.drawRectangle({
      x: PAGE_MARGIN,
      y,
      width: rowWidth,
      height: ROW_HEIGHT,
      color: rgb(0.97, 0.97, 0.97),
      borderColor: rgb(0.88, 0.88, 0.88),
      borderWidth: 0.5,
    });

    // Color swatch
    page.drawRectangle({
      x: PAGE_MARGIN,
      y,
      width: SWATCH_WIDTH,
      height: ROW_HEIGHT,
      color: rgb(r, g, b),
    });

    // Swatch / info divider
    page.drawLine({
      start: { x: PAGE_MARGIN + SWATCH_WIDTH, y },
      end: { x: PAGE_MARGIN + SWATCH_WIDTH, y: y + ROW_HEIGHT },
      thickness: 0.5,
      color: rgb(0.88, 0.88, 0.88),
    });

    const labelY = y + ROW_HEIGHT - 20;
    const valueY = y + ROW_HEIGHT - 34;

    const columns = [
      { label: 'HEX', value: hex },
      { label: 'RGB', value: `${rr}, ${rg}, ${rb}` },
      { label: 'CMYK', value: `${cr}, ${cg}, ${cb}, ${ck}` },
    ];

    columns.forEach((col, i) => {
      const x = infoX + i * colWidth;

      // Label
      page.drawText(col.label, {
        x,
        y: labelY,
        size: 8,
        font,
        color: rgb(0.6, 0.6, 0.6),
      });

      // Value — selectable text
      page.drawText(col.value, {
        x,
        y: valueY,
        size: 11,
        font: fontBold,
        color: rgb(0.1, 0.1, 0.1),
      });
    });

    y -= ROW_HEIGHT + ROW_GAP;
  });

  // ---- Footer ----
  const footerY = PAGE_MARGIN;
  page.drawLine({
    start: { x: PAGE_MARGIN, y: footerY + 14 },
    end: { x: PAGE_WIDTH - PAGE_MARGIN, y: footerY + 14 },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.85),
  });
  page.drawText('Generated by Palette Builder', {
    x: PAGE_WIDTH - PAGE_MARGIN - font.widthOfTextAtSize('Generated by Palette Builder', 9),
    y: footerY,
    size: 9,
    font,
    color: rgb(0.7, 0.7, 0.7),
  });

  // ---- Save ----
  const pdfBytes = await pdfDoc.save();
  const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'palette.pdf';
  a.click();
  URL.revokeObjectURL(url);
};